Controllers/PartsController.cs
//------------------------------------------------------------------------------
//----- PartsController.cs-----------------------------------------------------
//------------------------------------------------------------------------------

//-------1---------2---------3---------4---------5---------6---------7---------8
//       01234567890123456789012345678901234567890123456789012345678901234567890
//-------+---------+---------+---------+---------+---------+---------+---------+

// copyright:   2012 WiM - USGS

//    authors:  Tonia Roddick USGS Wisconsin Internet Mapping
//              
//  
//   purpose:   Display a master Parts page and link to individual parts pages 
//
//discussion:   
//
//     

#region Comments
// 07.22.13 - TR - Modifier has become ApplicationMethod and Formulation
// 05.30.13 - TR - Added Species
// 05.29.13 - TR - Added Product
// 05.28.13 - TR - Hooked into services
// 04.23.13 - TR - Created

#endregion

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Objects.DataClasses;
using System.Text;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Text.RegularExpressions;

using RestSharp;
using BLTServices;
using BLTServices.Authentication;
using BLTServices.Resources;
using BLTWeb.Utilities;
using BLTWeb.Models;
using BLTWeb.Helpers;

namespace BLTWeb.Controllers
{
    [RequireSSL]
    [Authorize]
    public class PartsController : Controller
    {
        //
        // GET: /Parts/
        public ActionResult Index()
        {
            BLTServiceCaller serviceCaller = BLTServiceCaller.Instance;
            var request = new RestRequest();

            //get the role of user logged in
            ViewData["Role"] = GetLoggedInMember();
            
            #region AI
            request = new RestRequest();
            request.Resource = "/ActiveIngredients?publishedDate={date}";
            request.RootElement = "ArrayOfACTIVE_INGREDIENT";
            List<ACTIVE_INGREDIENT> aiList = serviceCaller.Execute<List<ACTIVE_INGREDIENT>>(request);
            ViewData["AIList"] = aiList;
            #endregion AI

            #region AI Class
            request = new RestRequest();
            request.Resource = "/AIClasses?publishedDate={date}";
            request.RootElement = "ArrayOfAI_CLASS";
            List<AI_CLASS> AIClassList = serviceCaller.Execute<List<AI_CLASS>>(request);
            ViewData["AIClassList"] = AIClassList;
            #endregion  AI Class

            #region CropUse
            request = new RestRequest();
            request.Resource = "/CropUses?publishedDate={date}";
            request.RootElement = "ArrayOfCROP_USE";
            List<CROP_USE> CropUseList = serviceCaller.Execute<List<CROP_USE>>(request);
            ViewData["CropUseList"] = CropUseList;
            #endregion CropUse

            #region ApplicationMethod
            request = new RestRequest();
            request.Resource = "/ApplicationMethods?publishedDate={date}";
            request.RootElement = "ArrayOfAPPLICATION_METHOD";
            List<APPLICATION_METHOD> AppMethodsList = serviceCaller.Execute<List<APPLICATION_METHOD>>(request);
            ViewData["AppMethodsList"] = AppMethodsList;
            #endregion Modifier

            #region Organization
            request = new RestRequest();
            request.Resource = "/Organizations/";
            request.RootElement = "ArrayOfORGANIZATION";
            List<ORGANIZATION> OrganizationList = serviceCaller.Execute<List<ORGANIZATION>>(request);
            ViewData["OrganizationList"] = OrganizationList;
            #endregion  Organization

            #region Product
            //uses autocomplete
            #endregion Product

            #region Event
            request = new RestRequest();
            request.Resource = "/Events";
            request.RootElement = "ArrayOfEVENT";
            List<EVENT> eventList = serviceCaller.Execute<List<EVENT>>(request);
            ViewData["EventList"] = eventList;
            #endregion Event

            #region LimitationCodes
            request.Resource = "/Limitations?publishedDate={date}";
            request.RootElement = "ArrayOfLIMITATIONS";
            List<LIMITATION> LimitationList = serviceCaller.Execute<List<LIMITATION>>(request);
            ViewData["LimitationList"] = LimitationList;
            #endregion LimitationCodes

            #region Formulation
            request = new RestRequest();
            request.Resource = "/Formulations?publishedDate={date}";
            request.RootElement = "ArrayOfFORMULATION";
            List<FORMULATION> formulationList = serviceCaller.Execute<List<FORMULATION>>(request);
            ViewData["FormulationsList"] = formulationList;
            #endregion Formulation           
          
            #region Division
            request = new RestRequest();
            request.Resource = "/Divisions/";
            request.RootElement = "ArrayOfDIVISION";
            List<DIVISION> DivisionList = serviceCaller.Execute<List<DIVISION>>(request);
            ViewData["DivisionList"] = DivisionList;
            #endregion Division

            return View();
        }

        #region AI

        //want to do something, depends on Create for AI
        [HttpPost]
        public ActionResult AI(FormCollection fc, string Create)
        {
            try
            {
                int AI_Id = 0;
                if (Create == "Add New")
                {
                    return RedirectToAction("AINew");
                }
                else if (Create == "Edit")
                {
                    //edit
                    AI_Id = Convert.ToInt32(fc["ID"]);
                    if (AI_Id == 0)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        //send them to edit page                        
                        return RedirectToAction("AIEdit", new { id = AI_Id });
                    }
                }
                else
                {
                    //Copy to New
                    AI_Id = Convert.ToInt32(fc["ID"]);
                    if (AI_Id == 0)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        //send them to copy to new page
                        return RedirectToAction("AICopy", new { id = AI_Id });
                    }
                }
            }
            catch (Exception e)
            {
                return View(e.ToString());
            }
        }

        //edit page
        public ActionResult AIEdit(int id)
        {
            //get the logged in user's role
            ViewData["Role"] = GetLoggedInMember();
            BLTServiceCaller serviceCaller = BLTServiceCaller.Instance;
            
            //get this AI based on it's ID

            ACTIVE_INGREDIENT thisAI = GetAnAI(id);

            //get all the AI classes for dropdown
            var request = new RestRequest();
            request.Resource = "/AIClasses?publishedDate={date}";
            request.RootElement = "ArrayOfAI_CLASS";
            List<AI_CLASS> AIClassList = serviceCaller.Execute<List<AI_CLASS>>(request);
            ViewData["AIClassList"] = AIClassList;

            //get the AI's AI_Classes
            request = new RestRequest();
            request.Resource = "/ActiveIngredients/{activeIngredientID}/AIClass?publishedDate={date}";
            request.RootElement = "ArrayOfAI_CLASS";
            request.AddParameter("activeIngredientID", thisAI.ACTIVE_INGREDIENT_ID, ParameterType.UrlSegment);
            List<AI_CLASS> AIClasses = serviceCaller.Execute<List<AI_CLASS>>(request);
            
            //Populate model for view
            AIModel thisAIModel = new AIModel();

            //the AI
            thisAIModel.AI = thisAI;

            if (AIClasses != null)
            {
                ViewData["AIClasses"] = AIClasses.OrderBy(a => a.AI_CLASS_NAME).ToList();
                //the AIClass IDs for hidden input to maintain
                string aicID = string.Empty;
                string trimmedAicID = string.Empty;
                if (AIClasses.Count >= 1)
                {//store each entityID (so the correct version can be gotten)
                    foreach (AI_CLASS aic in AIClasses)
                    {
                        aicID += aic.ID + ",";
                    }
                    trimmedAicID = aicID.TrimEnd(',', ' ');
                }
                thisAIModel.AIClassesToAdd = trimmedAicID;
            }

            //get the Products linked to this AI by ID
            serviceCaller = BLTServiceCaller.Instance;
            request = new RestRequest();
            request.Resource = "/ActiveIngredients/{activeIngredientID}/Product?publishedDate={date}";
            request.RootElement = "ArrayOfPRODUCT";
            request.AddParameter("activeIngredientID", thisAI.ACTIVE_INGREDIENT_ID, ParameterType.UrlSegment);
            List<PRODUCT> AIProducts = serviceCaller.Execute<List<PRODUCT>>(request);
            ViewData["AIProducts"] = AIProducts;

            return View("AI/AIEdit", thisAIModel);
        }
        
        //Post the edit to update the AI
        [HttpPost]
        public ActionResult AI_Edit(int id, AIModel updatedAIModel)
        {
            ACTIVE_INGREDIENT thisAI = updatedAIModel.AI;
            string AIClasses2Add = updatedAIModel.AIClassesToAdd;
            string AIClasses2Remove = updatedAIModel.AIClassesIDsToRemove;            

            BLTServiceCaller serviceCaller = BLTServiceCaller.Instance;
            var request = new RestRequest();
            //see if any products have been related or any removed from relationship
            //if prodsToRemove != null -> expire those

Views/Parts/ApplicationMethods/ApplicationMethodsEdit.cshtml
@*
07.22.13 - TR - Changed from Modifier to Application Method
05.23.13 - TR - Hooked into services
04.23.13 - TR - Created *@

@*
/* Authors:
 *      Tonia Roddick (troddick@usgs.gov)
 * Copyright:
 *      2012 USGS - WiM
 * Purpose:
 *      Display the Modifiers Part Edit page 
 */
 *@
 
@using BLTServices;
@using BLTWeb.Assets.Resources;

@model BLTServices.APPLICATION_METHOD
           
@{
    ViewBag.Title = "Edit Application Method";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="loading"><div id="loadingcontent"><p id="loadingspinner" style=""><img src="@Url.Content("~/Assets/Images/LoadingOrange110.gif")" /></p></div></div>

<div class="partsTitle">
    <div style="float:left">Bulletins Components - Application Method</div>
    @if (ViewData["Role"] == "Admin")
    {
        <div style="float:left">&nbsp;&nbsp;
            @Html.ActionLink("Expire", "ExpireApplicationMethod", "Parts", new { id = Model.ID}, new { onclick = "return confirm('Are you sure you want to expire Application Method " + Model.METHOD + "?');", @class = "BLTButton blue" })
        </div>
    }
    <span id="errorSection" class="failureNotification"><asp:Literal ID="ErrorMessage" runat="server"></asp:Literal></span>
</div>

@if (ViewData["Role"] == "Admin" || ViewData["Role"] == "Publish")
{
    using (Html.BeginForm("ApplicationMethods_Edit", "Parts", new { id = Model.ID }, FormMethod.Post, new { @id = "form0" }))
    {
        <div class="siteColumn">
    
         <input type="hidden" name="ID" value="@Model.ID" />
         <input type="hidden" name="APPLICATION_METHOD_ID" value="@Model.APPLICATION_METHOD_ID" />

            <div class="ui-grid-a">
                <div data-role="fieldcontain">
	                <div class="ui-block-a"><span class="required">@Html.Label(ResStrings.AppMethod_Label)</span></div>
	                <div class="ui-block-b"><input type="text" class="required bltTextInput ui-shadow-inset" name="METHOD" data-mini="true" value="@Model.METHOD"  /></div>
                </div>
             </div>
	
            <br clear="all" />
    
            <div id="formSubmitDiv" class="formSection">
               <div class="leftSideSubmit">
                   <div class="submitDiv"><div class="darkButtonBorder"><input type="submit" name="Create" class="submit" value="Save" /></div></div>
                   <div class="cancelDiv"><div class="lightButtonBorder"><input type="reset" id="resetButton" class="cancel" value="Cancel" onclick="cancelClick();" /></div></div>
               </div>
            </div>

     </div>
    }
}
else
{
    <div>You are not authorized to edit a Application Method.</div>
}

<script type="text/javascript">
    function cancelClick() {
        $("#loading").fadeIn();
        window.location.href = '@Url.Action("Index", "Parts")'
    };
</script>

<script type="text/javascript">
    function loading() {
        $("#loading").fadeIn();
    }
</script>

<script type="text/javascript">
    $("#form0").submit(function () {
        var MISSING = "ui-req";
        var SelMISSING = "ui-Sel-req";

        var requiredInput = $('input[class*="required"]');
        var requiredSelect = $('select[class*="required"]');
        var requiredTextArea = $('textarea[class*="required"]');

        var Ierr = false;
        var Serr = false;
        var Terr = false;
        var missingMsg = "The highlighted fields are required.";

        // Reset the previously highlighted input fields  
        requiredInput.each(function (index) {
            $(this).removeClass(MISSING);
            $(this).addClass("ui-shadow-inset");
        });
        // Reset the previously highlighted select fields  
        requiredSelect.each(function (index) {
            $(this).removeClass(MISSING);
            $(this).addClass("ui-shadow-inset");
        });
        // Reset the previously highlighted textarea fields  
        requiredTextArea.each(function (index) {
            $(this).removeClass(MISSING);
            $(this).addClass("ui-shadow-inset");
        });
        // Perform form validation (input field)
        requiredInput.each(function (index) {
            if ($(this).val() == null || $(this).val() == "") {
                $(this).addClass(MISSING);
                $(this).removeClass("ui-shadow-inset");
                Ierr = true;
            }
        });
        // Perform form validation (select field) 
        requiredSelect.each(function (index) {
            var ind = $(this).context.selectedIndex;
            if (ind == 0) {
                $(this).addClass(SelMISSING);
                Serr = true;
            }
        });
        // Perform form validation (textarea field)
        requiredTextArea.each(function (index) {
            if ($(this).val() == null || $(this).val() == "") {
                $(this).addClass(MISSING);
                $(this).removeClass("ui-shadow-inset");
                Terr = true;
            }
        });
        // Check if validation fails
        if (Ierr == true || Serr == true || Terr == true) {
            $("#errorSection").append(missingMsg);
            return false;
        }
        else {
            loading();
            return true;
        }
    });
</script>

Views/Parts/ApplicationMethods/ApplicationMethodsNew.cshtml
@*
07.22.13 - TR - Changed from Modifier to Application Method
05.23.13 - TR - Hooked into services
04.23.13 - TR - Created *@

@*
/* Authors:
 *      Tonia Roddick (troddick@usgs.gov)
 * Copyright:
 *      2012 USGS - WiM
 * Purpose:
 *      Display the Application Methods Part Add New page 
 */
 *@
 
@using BLTServices;
@using BLTWeb.Assets.Resources;

@{
    ViewBag.Title = "New ApplicationMethod";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="loading"><div id="loadingcontent"><p id="loadingspinner" style=""><img src="@Url.Content("~/Assets/Images/LoadingOrange110.gif")" /></p></div></div>

<div class="partsTitle">
    Manage Bulletins Components - Application Method
    <span id="errorSection" class="failureNotification"><asp:Literal ID="ErrorMessage" runat="server"></asp:Literal></span>
</div>

@using (Html.BeginForm("ApplicationMethods_New", "Parts", FormMethod.Post, new { @id = "form0" }))
{
    <div class="siteColumn">

        <div class="ui-grid-a">
            <div data-role="fieldcontain">
    	        <div class="ui-block-a"><span class="required">@Html.Label(ResStrings.AppMethod_Label)</span></div>
	            <div class="ui-block-b"><input type="text" class="required bltTextInput ui-shadow-inset" name="METHOD" data-mini="true" /></div>
            </div>
        </div>
	
        <br clear="all" />
    
        <div id="formSubmitDiv" class="formSection">
            <div class="leftSideSubmit">
                <div class="submitDiv"><div class="darkButtonBorder"><input type="submit" name="Create" class="submit" value="Save" /></div></div>
                <div class="cancelDiv"><div class="lightButtonBorder"><input type="reset" id="resetButton" class="cancel" value="Cancel" onclick="cancelClick();" /></div></div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    function loading() {
        $("#loading").fadeIn();
    }
</script>
<script type="text/javascript">
    function cancelClick() {
        $("#loading").fadeIn();
        window.location.href = '@Url.Action("Index", "Parts")'
    };
</script>
<script type="text/javascript">
    $("#form0").submit(function () {
        var MISSING = "ui-req";
        var SelMISSING = "ui-Sel-req";

        var requiredInput = $('input[class*="required"]');
        var requiredSelect = $('select[class*="required"]');
        var requiredTextArea = $('textarea[class*="required"]');

        var Ierr = false;
        var Serr = false;
        var Terr = false;
        var missingMsg = "The highlighted fields are required.";

        // Reset the previously highlighted input fields  
        requiredInput.each(function (index) {
            $(this).removeClass(MISSING);
            $(this).addClass("ui-shadow-inset");
        });
        // Reset the previously highlighted select fields  
        requiredSelect.each(function (index) {
            $(this).removeClass(MISSING);
            $(this).addClass("ui-shadow-inset");
        });
        // Reset the previously highlighted textarea fields  
        requiredTextArea.each(function (index) {
            $(this).removeClass(MISSING);
            $(this).addClass("ui-shadow-inset");
        });
        // Perform form validation (input field)
        requiredInput.each(function (index) {
            if ($(this).val() == null || $(this).val() == "") {
                $(this).addClass(MISSING);
                $(this).removeClass("ui-shadow-inset");
                Ierr = true;
            }
        });
        // Perform form validation (select field) 
        requiredSelect.each(function (index) {
            var ind = $(this).context.selectedIndex;
            if (ind == 0) {
                $(this).addClass(SelMISSING);
                Serr = true;
            }
        });
        // Perform form validation (textarea field)
        requiredTextArea.each(function (index) {
            if ($(this).val() == null || $(this).val() == "") {
                $(this).addClass(MISSING);
                $(this).removeClass("ui-shadow-inset");
                Terr = true;
            }
        });
        // Check if validation fails
        if (Ierr == true || Serr == true || Terr == true) {
            $("#errorSection").append(missingMsg);
            return false;
        }
        else {
            loading();
            return true;
        }
    });
</script>